server:
  port: 8086

spring:
  application:
    name: review-service
  datasource:
    url: jdbc:mysql://localhost:3306/review_db
    username: root
    password: hag11990
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: medibook-super-secret-key-must-be-at-least-256-bits-long-for-hs256

services:
  appointment-url: http://localhost:8080/internal/appointments
  provider-url:    http://localhost:8080/internal/providers
  notification-url: http://localhost:8080/internal/notifications

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    com.medibook.review: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true